spring:
  profiles:
    active:
      -  cat
      -  EN
      -  prod
guru:
  username: YmlDbUser
  password: YmlDBPassword
  jdbcUrl: YmlUrl

---
spring:
  profiles: prod
guru:
  username: YmlProdDBUser
  password: YmlProdDBPassword
  jdbcUrl: YmlProdUrl